### ISSUE TITLE
[Security] Workflow build.yml is using vulnerable action Bogdanp/setup-racket

### ISSUE THREAD

**Issue by igibek** [saadatm/ghalib#1]
The workflow build.yml is referencing action Bogdanp/setup-racket using references v1.1. However this reference is missing the commit [76daca87cfa0b8c13f8ef57f12e03c6b5d9dcfd8](https://github.com/Bogdanp/setup-racket/commits/76daca87cfa0b8c13f8ef57f12e03c6b5d9dcfd8) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by saadatm** [comment]
Fixed in c4f0ac8f2a555e79bfccc07b99b2a31fdde5de7b.
